const pictureArr = [
  {
    jpg: "content/pic-1/1.jpg",
    webp: "content/pic-1/1.webp",
    avif: "content/pic-1/1.avif",
    desc: "Geralt with Ciri sitting on a cliff",
    objPos: "54%",
  },
  {
    jpg: "content/pic-2/2.jpg",
    webp: "content/pic-2/2.webp",
    avif: "content/pic-2/2.avif",
    desc: "Ciri Facing Wild Hunt soldier",
    objPos: "23%",
  },
  {
    jpg: "content/pic-3/3.jpg",
    webp: "content/pic-3/3.webp",
    avif: "content/pic-3/3.avif",
    desc: "Geralt, Lambert and Letho",
    objPos: "21%",
  },
  {
    jpg: "content/pic-4/4.jpg",
    webp: "content/pic-4/4.webp",
    avif: "content/pic-4/4.avif",
    desc: "Holy Tree",
    objPos: "23%",
  },
  {
    jpg: "content/pic-5/5.jpg",
    webp: "content/pic-5/5.webp",
    avif: "content/pic-5/5.avif",
    desc: "Geralt with Syanna",
    objPos: "75%",
  },
  {
    jpg: "content/pic-6/6.jpg",
    webp: "content/pic-6/6.webp",
    avif: "content/pic-6/6.avif",
    desc: "Geralt strike sword into Eredin",
    objPos: "21%",
  },
  {
    jpg: "content/pic-7/7.jpg",
    webp: "content/pic-7/7.webp",
    avif: "content/pic-7/7.avif",
    desc: "Yennefer preparing to defend Kaer Morhen",
    objPos: "54%",
  },
  {
    jpg: "content/pic-8/8.jpg",
    webp: "content/pic-8/8.webp",
    avif: "content/pic-8/8.avif",
    desc: "Geralt first arrival to Toussaint in Blood and Wine DLC",
    objPos: "57%",
  },
  {
    jpg: "content/pic-9/9.jpg",
    webp: "content/pic-9/9.webp",
    avif: "content/pic-9/9.avif",
    desc: "Geralt warming his hand",
    objPos: "64%",
  },
  {
    jpg: "content/pic-10/10.jpg",
    webp: "content/pic-10/10.webp",
    avif: "content/pic-10/10.avif",
    desc: "Yennefer saved Geralt with portal",
    objPos: "19%",
  },
  {
    jpg: "content/pic-11/11.jpg",
    webp: "content/pic-11/11.webp",
    avif: "content/pic-11/11.avif",
    desc: "Wild Hunt Eredin burning village",
    objPos: "45%",
  },
  {
    jpg: "content/pic-12/12.jpg",
    webp: "content/pic-12/12.webp",
    avif: "content/pic-12/12.avif",
    desc: "Geralt about to go into the magical book",
    objPos: "56%",
  },
];

export default pictureArr;
